apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ${tls_authority}
    server: ${endpoint}
  name: ${name}
contexts:
- context:
    cluster: ${name}
    user: ${name}
  name: ${name}
current-context: ${name}
kind: Config
preferences: {}
users:
- name: ${name}
  user:
    client-certificate-data: ${tls_certificate}
    client-key-data: ${tls_key}
